# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a1492f72f5a748dd163639f9d7618bc4f7797ac6719ae22a6690ab4c4033da345b48867536d84560cb728d41d72cf399af7d508590a54de40a6235232420a9b

test:
  secret_key_base: eeafbefccaa3aa48d05850d50b0a15e4baa0b6271a94cb3c1cba7c8acb8a073626655a4b71aa7065f3c58c28c972715c83a6ea8978ff3d06ff3bf69119cb3dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
